/*
ONDC Protocol API for retail (grocery, f&b)

ONDC Protocol API specification, which includes statutory requirements for packaged commodities and pre-packaged food This is an adaptation of Beckn Core version 0.9.3

API version: 1.0.27
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// FulfillmentEnd Details on the end of fulfillment
type FulfillmentEnd struct {
	Location *Location `json:"location,omitempty"`
	Time *Time `json:"time,omitempty"`
	Instructions *Descriptor `json:"instructions,omitempty"`
	Contact *Contact `json:"contact,omitempty"`
	Person *Person `json:"person,omitempty"`
	Authorization *Authorization `json:"authorization,omitempty"`
}

// NewFulfillmentEnd instantiates a new FulfillmentEnd object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFulfillmentEnd() *FulfillmentEnd {
	this := FulfillmentEnd{}
	return &this
}

// NewFulfillmentEndWithDefaults instantiates a new FulfillmentEnd object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFulfillmentEndWithDefaults() *FulfillmentEnd {
	this := FulfillmentEnd{}
	return &this
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *FulfillmentEnd) GetLocation() Location {
	if o == nil || isNil(o.Location) {
		var ret Location
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentEnd) GetLocationOk() (*Location, bool) {
	if o == nil || isNil(o.Location) {
    return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *FulfillmentEnd) HasLocation() bool {
	if o != nil && !isNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given Location and assigns it to the Location field.
func (o *FulfillmentEnd) SetLocation(v Location) {
	o.Location = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *FulfillmentEnd) GetTime() Time {
	if o == nil || isNil(o.Time) {
		var ret Time
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentEnd) GetTimeOk() (*Time, bool) {
	if o == nil || isNil(o.Time) {
    return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *FulfillmentEnd) HasTime() bool {
	if o != nil && !isNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given Time and assigns it to the Time field.
func (o *FulfillmentEnd) SetTime(v Time) {
	o.Time = &v
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *FulfillmentEnd) GetInstructions() Descriptor {
	if o == nil || isNil(o.Instructions) {
		var ret Descriptor
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentEnd) GetInstructionsOk() (*Descriptor, bool) {
	if o == nil || isNil(o.Instructions) {
    return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *FulfillmentEnd) HasInstructions() bool {
	if o != nil && !isNil(o.Instructions) {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given Descriptor and assigns it to the Instructions field.
func (o *FulfillmentEnd) SetInstructions(v Descriptor) {
	o.Instructions = &v
}

// GetContact returns the Contact field value if set, zero value otherwise.
func (o *FulfillmentEnd) GetContact() Contact {
	if o == nil || isNil(o.Contact) {
		var ret Contact
		return ret
	}
	return *o.Contact
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentEnd) GetContactOk() (*Contact, bool) {
	if o == nil || isNil(o.Contact) {
    return nil, false
	}
	return o.Contact, true
}

// HasContact returns a boolean if a field has been set.
func (o *FulfillmentEnd) HasContact() bool {
	if o != nil && !isNil(o.Contact) {
		return true
	}

	return false
}

// SetContact gets a reference to the given Contact and assigns it to the Contact field.
func (o *FulfillmentEnd) SetContact(v Contact) {
	o.Contact = &v
}

// GetPerson returns the Person field value if set, zero value otherwise.
func (o *FulfillmentEnd) GetPerson() Person {
	if o == nil || isNil(o.Person) {
		var ret Person
		return ret
	}
	return *o.Person
}

// GetPersonOk returns a tuple with the Person field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentEnd) GetPersonOk() (*Person, bool) {
	if o == nil || isNil(o.Person) {
    return nil, false
	}
	return o.Person, true
}

// HasPerson returns a boolean if a field has been set.
func (o *FulfillmentEnd) HasPerson() bool {
	if o != nil && !isNil(o.Person) {
		return true
	}

	return false
}

// SetPerson gets a reference to the given Person and assigns it to the Person field.
func (o *FulfillmentEnd) SetPerson(v Person) {
	o.Person = &v
}

// GetAuthorization returns the Authorization field value if set, zero value otherwise.
func (o *FulfillmentEnd) GetAuthorization() Authorization {
	if o == nil || isNil(o.Authorization) {
		var ret Authorization
		return ret
	}
	return *o.Authorization
}

// GetAuthorizationOk returns a tuple with the Authorization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentEnd) GetAuthorizationOk() (*Authorization, bool) {
	if o == nil || isNil(o.Authorization) {
    return nil, false
	}
	return o.Authorization, true
}

// HasAuthorization returns a boolean if a field has been set.
func (o *FulfillmentEnd) HasAuthorization() bool {
	if o != nil && !isNil(o.Authorization) {
		return true
	}

	return false
}

// SetAuthorization gets a reference to the given Authorization and assigns it to the Authorization field.
func (o *FulfillmentEnd) SetAuthorization(v Authorization) {
	o.Authorization = &v
}

func (o FulfillmentEnd) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !isNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	if !isNil(o.Instructions) {
		toSerialize["instructions"] = o.Instructions
	}
	if !isNil(o.Contact) {
		toSerialize["contact"] = o.Contact
	}
	if !isNil(o.Person) {
		toSerialize["person"] = o.Person
	}
	if !isNil(o.Authorization) {
		toSerialize["authorization"] = o.Authorization
	}
	return json.Marshal(toSerialize)
}

type NullableFulfillmentEnd struct {
	value *FulfillmentEnd
	isSet bool
}

func (v NullableFulfillmentEnd) Get() *FulfillmentEnd {
	return v.value
}

func (v *NullableFulfillmentEnd) Set(val *FulfillmentEnd) {
	v.value = val
	v.isSet = true
}

func (v NullableFulfillmentEnd) IsSet() bool {
	return v.isSet
}

func (v *NullableFulfillmentEnd) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFulfillmentEnd(val *FulfillmentEnd) *NullableFulfillmentEnd {
	return &NullableFulfillmentEnd{value: val, isSet: true}
}

func (v NullableFulfillmentEnd) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFulfillmentEnd) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


