/*
ONDC Protocol Core API

ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SelectPostRequest struct for SelectPostRequest
type SelectPostRequest struct {
	Context Context `json:"context"`
	Message SelectPostRequestMessage `json:"message"`
}

// NewSelectPostRequest instantiates a new SelectPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSelectPostRequest(context Context, message SelectPostRequestMessage) *SelectPostRequest {
	this := SelectPostRequest{}
	this.Context = context
	this.Message = message
	return &this
}

// NewSelectPostRequestWithDefaults instantiates a new SelectPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSelectPostRequestWithDefaults() *SelectPostRequest {
	this := SelectPostRequest{}
	return &this
}

// GetContext returns the Context field value
func (o *SelectPostRequest) GetContext() Context {
	if o == nil {
		var ret Context
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *SelectPostRequest) GetContextOk() (*Context, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *SelectPostRequest) SetContext(v Context) {
	o.Context = v
}

// GetMessage returns the Message field value
func (o *SelectPostRequest) GetMessage() SelectPostRequestMessage {
	if o == nil {
		var ret SelectPostRequestMessage
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *SelectPostRequest) GetMessageOk() (*SelectPostRequestMessage, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *SelectPostRequest) SetMessage(v SelectPostRequestMessage) {
	o.Message = v
}

func (o SelectPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["context"] = o.Context
	}
	if true {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableSelectPostRequest struct {
	value *SelectPostRequest
	isSet bool
}

func (v NullableSelectPostRequest) Get() *SelectPostRequest {
	return v.value
}

func (v *NullableSelectPostRequest) Set(val *SelectPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSelectPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSelectPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSelectPostRequest(val *SelectPostRequest) *NullableSelectPostRequest {
	return &NullableSelectPostRequest{value: val, isSet: true}
}

func (v NullableSelectPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSelectPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


