/*
ONDC Protocol Core API

ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// OnSelectPostRequestMessageOrderItemsInnerAllOf struct for OnSelectPostRequestMessageOrderItemsInnerAllOf
type OnSelectPostRequestMessageOrderItemsInnerAllOf struct {
	Quantity *ItemQuantity `json:"quantity,omitempty"`
}

// NewOnSelectPostRequestMessageOrderItemsInnerAllOf instantiates a new OnSelectPostRequestMessageOrderItemsInnerAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOnSelectPostRequestMessageOrderItemsInnerAllOf() *OnSelectPostRequestMessageOrderItemsInnerAllOf {
	this := OnSelectPostRequestMessageOrderItemsInnerAllOf{}
	return &this
}

// NewOnSelectPostRequestMessageOrderItemsInnerAllOfWithDefaults instantiates a new OnSelectPostRequestMessageOrderItemsInnerAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOnSelectPostRequestMessageOrderItemsInnerAllOfWithDefaults() *OnSelectPostRequestMessageOrderItemsInnerAllOf {
	this := OnSelectPostRequestMessageOrderItemsInnerAllOf{}
	return &this
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *OnSelectPostRequestMessageOrderItemsInnerAllOf) GetQuantity() ItemQuantity {
	if o == nil || isNil(o.Quantity) {
		var ret ItemQuantity
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OnSelectPostRequestMessageOrderItemsInnerAllOf) GetQuantityOk() (*ItemQuantity, bool) {
	if o == nil || isNil(o.Quantity) {
    return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *OnSelectPostRequestMessageOrderItemsInnerAllOf) HasQuantity() bool {
	if o != nil && !isNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given ItemQuantity and assigns it to the Quantity field.
func (o *OnSelectPostRequestMessageOrderItemsInnerAllOf) SetQuantity(v ItemQuantity) {
	o.Quantity = &v
}

func (o OnSelectPostRequestMessageOrderItemsInnerAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	return json.Marshal(toSerialize)
}

type NullableOnSelectPostRequestMessageOrderItemsInnerAllOf struct {
	value *OnSelectPostRequestMessageOrderItemsInnerAllOf
	isSet bool
}

func (v NullableOnSelectPostRequestMessageOrderItemsInnerAllOf) Get() *OnSelectPostRequestMessageOrderItemsInnerAllOf {
	return v.value
}

func (v *NullableOnSelectPostRequestMessageOrderItemsInnerAllOf) Set(val *OnSelectPostRequestMessageOrderItemsInnerAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableOnSelectPostRequestMessageOrderItemsInnerAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableOnSelectPostRequestMessageOrderItemsInnerAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOnSelectPostRequestMessageOrderItemsInnerAllOf(val *OnSelectPostRequestMessageOrderItemsInnerAllOf) *NullableOnSelectPostRequestMessageOrderItemsInnerAllOf {
	return &NullableOnSelectPostRequestMessageOrderItemsInnerAllOf{value: val, isSet: true}
}

func (v NullableOnSelectPostRequestMessageOrderItemsInnerAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOnSelectPostRequestMessageOrderItemsInnerAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


