/*
ONDC Protocol Core API

ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// OrderItemsInner struct for OrderItemsInner
type OrderItemsInner struct {
	Id Id `json:"id"`
	Quantity *Selected `json:"quantity,omitempty"`
}

// NewOrderItemsInner instantiates a new OrderItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderItemsInner(id Id) *OrderItemsInner {
	this := OrderItemsInner{}
	this.Id = id
	return &this
}

// NewOrderItemsInnerWithDefaults instantiates a new OrderItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderItemsInnerWithDefaults() *OrderItemsInner {
	this := OrderItemsInner{}
	return &this
}

// GetId returns the Id field value
func (o *OrderItemsInner) GetId() Id {
	if o == nil {
		var ret Id
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OrderItemsInner) GetIdOk() (*Id, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OrderItemsInner) SetId(v Id) {
	o.Id = v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *OrderItemsInner) GetQuantity() Selected {
	if o == nil || isNil(o.Quantity) {
		var ret Selected
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderItemsInner) GetQuantityOk() (*Selected, bool) {
	if o == nil || isNil(o.Quantity) {
    return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *OrderItemsInner) HasQuantity() bool {
	if o != nil && !isNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given Selected and assigns it to the Quantity field.
func (o *OrderItemsInner) SetQuantity(v Selected) {
	o.Quantity = &v
}

func (o OrderItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	return json.Marshal(toSerialize)
}

type NullableOrderItemsInner struct {
	value *OrderItemsInner
	isSet bool
}

func (v NullableOrderItemsInner) Get() *OrderItemsInner {
	return v.value
}

func (v *NullableOrderItemsInner) Set(val *OrderItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderItemsInner(val *OrderItemsInner) *NullableOrderItemsInner {
	return &NullableOrderItemsInner{value: val, isSet: true}
}

func (v NullableOrderItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


