/*
ONDC Protocol Core API

ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RatingCategoriesPostRequest struct for RatingCategoriesPostRequest
type RatingCategoriesPostRequest struct {
	Context *Context `json:"context,omitempty"`
	RatingCategories []RatingCategory `json:"rating_categories,omitempty"`
}

// NewRatingCategoriesPostRequest instantiates a new RatingCategoriesPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRatingCategoriesPostRequest() *RatingCategoriesPostRequest {
	this := RatingCategoriesPostRequest{}
	return &this
}

// NewRatingCategoriesPostRequestWithDefaults instantiates a new RatingCategoriesPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRatingCategoriesPostRequestWithDefaults() *RatingCategoriesPostRequest {
	this := RatingCategoriesPostRequest{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *RatingCategoriesPostRequest) GetContext() Context {
	if o == nil || isNil(o.Context) {
		var ret Context
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RatingCategoriesPostRequest) GetContextOk() (*Context, bool) {
	if o == nil || isNil(o.Context) {
    return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *RatingCategoriesPostRequest) HasContext() bool {
	if o != nil && !isNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given Context and assigns it to the Context field.
func (o *RatingCategoriesPostRequest) SetContext(v Context) {
	o.Context = &v
}

// GetRatingCategories returns the RatingCategories field value if set, zero value otherwise.
func (o *RatingCategoriesPostRequest) GetRatingCategories() []RatingCategory {
	if o == nil || isNil(o.RatingCategories) {
		var ret []RatingCategory
		return ret
	}
	return o.RatingCategories
}

// GetRatingCategoriesOk returns a tuple with the RatingCategories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RatingCategoriesPostRequest) GetRatingCategoriesOk() ([]RatingCategory, bool) {
	if o == nil || isNil(o.RatingCategories) {
    return nil, false
	}
	return o.RatingCategories, true
}

// HasRatingCategories returns a boolean if a field has been set.
func (o *RatingCategoriesPostRequest) HasRatingCategories() bool {
	if o != nil && !isNil(o.RatingCategories) {
		return true
	}

	return false
}

// SetRatingCategories gets a reference to the given []RatingCategory and assigns it to the RatingCategories field.
func (o *RatingCategoriesPostRequest) SetRatingCategories(v []RatingCategory) {
	o.RatingCategories = v
}

func (o RatingCategoriesPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !isNil(o.RatingCategories) {
		toSerialize["rating_categories"] = o.RatingCategories
	}
	return json.Marshal(toSerialize)
}

type NullableRatingCategoriesPostRequest struct {
	value *RatingCategoriesPostRequest
	isSet bool
}

func (v NullableRatingCategoriesPostRequest) Get() *RatingCategoriesPostRequest {
	return v.value
}

func (v *NullableRatingCategoriesPostRequest) Set(val *RatingCategoriesPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRatingCategoriesPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRatingCategoriesPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRatingCategoriesPostRequest(val *RatingCategoriesPostRequest) *NullableRatingCategoriesPostRequest {
	return &NullableRatingCategoriesPostRequest{value: val, isSet: true}
}

func (v NullableRatingCategoriesPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRatingCategoriesPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


