/*
ONDC Protocol API for logistics

ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3

API version: 1.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// OnSelectPostRequest struct for OnSelectPostRequest
type OnSelectPostRequest struct {
	Context Context `json:"context"`
	Message *OnSelectPostRequestMessage `json:"message,omitempty"`
	Error *Error `json:"error,omitempty"`
}

// NewOnSelectPostRequest instantiates a new OnSelectPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOnSelectPostRequest(context Context) *OnSelectPostRequest {
	this := OnSelectPostRequest{}
	this.Context = context
	return &this
}

// NewOnSelectPostRequestWithDefaults instantiates a new OnSelectPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOnSelectPostRequestWithDefaults() *OnSelectPostRequest {
	this := OnSelectPostRequest{}
	return &this
}

// GetContext returns the Context field value
func (o *OnSelectPostRequest) GetContext() Context {
	if o == nil {
		var ret Context
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *OnSelectPostRequest) GetContextOk() (*Context, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *OnSelectPostRequest) SetContext(v Context) {
	o.Context = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *OnSelectPostRequest) GetMessage() OnSelectPostRequestMessage {
	if o == nil || isNil(o.Message) {
		var ret OnSelectPostRequestMessage
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OnSelectPostRequest) GetMessageOk() (*OnSelectPostRequestMessage, bool) {
	if o == nil || isNil(o.Message) {
    return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *OnSelectPostRequest) HasMessage() bool {
	if o != nil && !isNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given OnSelectPostRequestMessage and assigns it to the Message field.
func (o *OnSelectPostRequest) SetMessage(v OnSelectPostRequestMessage) {
	o.Message = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *OnSelectPostRequest) GetError() Error {
	if o == nil || isNil(o.Error) {
		var ret Error
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OnSelectPostRequest) GetErrorOk() (*Error, bool) {
	if o == nil || isNil(o.Error) {
    return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *OnSelectPostRequest) HasError() bool {
	if o != nil && !isNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given Error and assigns it to the Error field.
func (o *OnSelectPostRequest) SetError(v Error) {
	o.Error = &v
}

func (o OnSelectPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["context"] = o.Context
	}
	if !isNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !isNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableOnSelectPostRequest struct {
	value *OnSelectPostRequest
	isSet bool
}

func (v NullableOnSelectPostRequest) Get() *OnSelectPostRequest {
	return v.value
}

func (v *NullableOnSelectPostRequest) Set(val *OnSelectPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOnSelectPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOnSelectPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOnSelectPostRequest(val *OnSelectPostRequest) *NullableOnSelectPostRequest {
	return &NullableOnSelectPostRequest{value: val, isSet: true}
}

func (v NullableOnSelectPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOnSelectPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


