/*
ONDC Protocol API for logistics

ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3

API version: 1.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// OnInitPostRequestMessageOrderAddOnsInner struct for OnInitPostRequestMessageOrderAddOnsInner
type OnInitPostRequestMessageOrderAddOnsInner struct {
	Id *Id `json:"id,omitempty"`
}

// NewOnInitPostRequestMessageOrderAddOnsInner instantiates a new OnInitPostRequestMessageOrderAddOnsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOnInitPostRequestMessageOrderAddOnsInner() *OnInitPostRequestMessageOrderAddOnsInner {
	this := OnInitPostRequestMessageOrderAddOnsInner{}
	return &this
}

// NewOnInitPostRequestMessageOrderAddOnsInnerWithDefaults instantiates a new OnInitPostRequestMessageOrderAddOnsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOnInitPostRequestMessageOrderAddOnsInnerWithDefaults() *OnInitPostRequestMessageOrderAddOnsInner {
	this := OnInitPostRequestMessageOrderAddOnsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OnInitPostRequestMessageOrderAddOnsInner) GetId() Id {
	if o == nil || isNil(o.Id) {
		var ret Id
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OnInitPostRequestMessageOrderAddOnsInner) GetIdOk() (*Id, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OnInitPostRequestMessageOrderAddOnsInner) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given Id and assigns it to the Id field.
func (o *OnInitPostRequestMessageOrderAddOnsInner) SetId(v Id) {
	o.Id = &v
}

func (o OnInitPostRequestMessageOrderAddOnsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableOnInitPostRequestMessageOrderAddOnsInner struct {
	value *OnInitPostRequestMessageOrderAddOnsInner
	isSet bool
}

func (v NullableOnInitPostRequestMessageOrderAddOnsInner) Get() *OnInitPostRequestMessageOrderAddOnsInner {
	return v.value
}

func (v *NullableOnInitPostRequestMessageOrderAddOnsInner) Set(val *OnInitPostRequestMessageOrderAddOnsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOnInitPostRequestMessageOrderAddOnsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOnInitPostRequestMessageOrderAddOnsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOnInitPostRequestMessageOrderAddOnsInner(val *OnInitPostRequestMessageOrderAddOnsInner) *NullableOnInitPostRequestMessageOrderAddOnsInner {
	return &NullableOnInitPostRequestMessageOrderAddOnsInner{value: val, isSet: true}
}

func (v NullableOnInitPostRequestMessageOrderAddOnsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOnInitPostRequestMessageOrderAddOnsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


