/*
ONDC Protocol API for logistics

ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3

API version: 1.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// OrderProviderLocationsInner struct for OrderProviderLocationsInner
type OrderProviderLocationsInner struct {
	Id Id `json:"id"`
}

// NewOrderProviderLocationsInner instantiates a new OrderProviderLocationsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderProviderLocationsInner(id Id) *OrderProviderLocationsInner {
	this := OrderProviderLocationsInner{}
	this.Id = id
	return &this
}

// NewOrderProviderLocationsInnerWithDefaults instantiates a new OrderProviderLocationsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderProviderLocationsInnerWithDefaults() *OrderProviderLocationsInner {
	this := OrderProviderLocationsInner{}
	return &this
}

// GetId returns the Id field value
func (o *OrderProviderLocationsInner) GetId() Id {
	if o == nil {
		var ret Id
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OrderProviderLocationsInner) GetIdOk() (*Id, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OrderProviderLocationsInner) SetId(v Id) {
	o.Id = v
}

func (o OrderProviderLocationsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableOrderProviderLocationsInner struct {
	value *OrderProviderLocationsInner
	isSet bool
}

func (v NullableOrderProviderLocationsInner) Get() *OrderProviderLocationsInner {
	return v.value
}

func (v *NullableOrderProviderLocationsInner) Set(val *OrderProviderLocationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderProviderLocationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderProviderLocationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderProviderLocationsInner(val *OrderProviderLocationsInner) *NullableOrderProviderLocationsInner {
	return &NullableOrderProviderLocationsInner{value: val, isSet: true}
}

func (v NullableOrderProviderLocationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderProviderLocationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


